name: app_eleccion_delegado_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  #Para el manejo de estado (MVVM)
  lottie: ^3.1.2
  #Para animaciones atractivas en el splash
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8 #Recomendado para gestionar la sesion
  firebase_core: ^2.27.0
  geolocator: ^12.0.0
  cloud_firestore: ^4.15.8
  flutter_svg: ^2.0.10+1 #Para mostrar imágenes SVG

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  html: ^0.15.6
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/animations/success.json
    - assets/logo/logoConti.svg
    - assets/images/election_background.jpg
    - assets/candidatos/
  uses-material-design: true
